name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run dummy test
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: echo "CI is working ✅"
